obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.1525, -0.1228], [-0.1525, 0.1228], [0.1525, 0.1228], [0.1525, -0.1228]]
#robot_radius: 0.105

# 膨胀半径
inflation_radius: 0.1 #Albert was 0.2
cost_scaling_factor: 3.0

map_type: costmap

obstacle_layer:
  enabled:              true
  max_obstacle_height:  2.0
  min_obstacle_height:  0.0
  combination_method:   1
  # true needed for disabling global path planning through unknown space
  track_unknown_space:  true
  # The robot updates the threshold of the obstacle distance from the base coordinate system in the cost map.
  obstacle_range: 3.0
  # The robot clears obstacles in the cost map from the threshold of the base coordinate system.
  raytrace_range: 3.5
  publish_voxel_map: false
  observation_sources:  scan point_cloud
  scan:
    sensor_frame: laser
    data_type: LaserScan
    topic: "scan"
    marking: true
    clearing: true
    expected_update_rate: 0
  point_cloud:
    sensor_frame: camera_depth_frame
    data_type: PointCloud2
    topic: camera/depth/points
    #expected_update_rate: 0.5
    expected_update_rate: 0
    marking: true
    clearing: true
    min_obstacle_height: 0.1
    

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  # exponential rate at which the obstacle cost drops off
  cost_scaling_factor:  1.0

static_layer:
  enabled:              true
  map_topic:            "/map"

