local_costmap:
  # Coordinate frame and tf parameters
  # The "global_frame" parameter defines what coordinate frame the costmap should run in, in this case, we'll choose the /map frame.
  global_frame: odom
  # The "robot_base_frame" parameter defines the coordinate frame the costmap should reference for the base of the robot.
  robot_base_frame: base_footprint
  # Specifies the delay in transform (tf) data that is tolerable in seconds.
  transform_tolerance: 0.5
  # The "update_frequency" parameter determines the frequency, in Hz, at which the costmap will run its update loop.
  update_frequency: 10.0
  # The rate at which the cost map publishes visual information
  publish_frequency: 10.0
  # If true, the map service provided by the map server will initialize the cost map, otherwise it will be false.
  static_map: false
  # Whether or not to use a rolling window version of the costmap.
  # If the static_map parameter is set to true, this parameter must be set to false.
  rolling_window: true
  # The "width," "height," and "resolution" parameters set the width (meters), height (meters), and resolution (meters/cell) of the costmap.
  width: 2.5 #Albert was 2.5
  height: 2.5 #Albert was 2.5
  resolution: 0.05
