
# The name of the plugin for the global planner to use with move_base, see pluginlib documentation for more details on plugins.
#base_global_planner: "navfn/NavfnROS"
#base_global_planner: "global_planner/GlobalPlanner"
#base_global_planner: "carrot_planner/CarrotPlanner"


# The name of the plugin for the local planner to use with move_base see pluginlib documentation for more details on plugins.
#base_local_planner: "teb_local_planner/TebLocalPlannerROS"
#base_local_planner: "dwa_local_planner/DWAPlannerROS"

# 恢复行为。
recovery_behaviors:
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'aggressive_reset'
  #  type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'super_reset'
  #  type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'clearing_rotation'
    type: 'rotate_recovery/RotateRecovery'
    #- name: 'move_slow_and_clear'
    #type: 'move_slow_and_clear/MoveSlowAndClear'



# The rate in Hz at which to run the control loop and send velocity commands to the base.
controller_frequency: 10.0
# How long the planner will wait in seconds in an attempt to find a valid plan before space-clearing operations are performed.
planner_patience: 5.0
# How long the controller will wait in seconds without receiving a valid control before space-clearing operations are performed.
controller_patience: 5.0
# The distance away from the robot in meters beyond which obstacles will be cleared from the costmap when attempting to clear space in the map.
conservative_reset_dist: 5.0
# Whether or not to enable the move_base recovery behaviors to attempt to clear out space.
recovery_behavior_enabled: true
# Determines whether or not the robot will attempt an in-place rotation when attempting to clear out space.
clearing_rotation_allowed: true
# Determines whether or not to shutdown the costmaps of the node when move_base is in an inactive state
shutdown_costmaps: false
# How long in seconds to allow for oscillation before executing recovery behaviors.
oscillation_timeout: 10.0
# How far in meters the robot must move to be considered not to be oscillating.
oscillation_distance: 0.3
# The rate in Hz at which to run the global planning loop.
planner_frequency: 10.0 #0.0
# How many times to allow for planning retries before executing recovery behaviors.
max_planning_retries: -1.0

conservative_reset:
  reset_distance: 1.0
  #layer_names: [static_layer, obstacle_layer, inflation_layer]
  layer_names: [obstacle_layer]

aggressive_reset:
  reset_distance: 3.0
  #layer_names: [static_layer, obstacle_layer, inflation_layer]
  layer_names: [obstacle_layer]

super_reset:
  reset_distance: 5.0
  #layer_names: [static_layer, obstacle_layer, inflation_layer]
  layer_names: [obstacle_layer]

move_slow_and_clear:
  clearing_distance: 0.1
  limited_trans_speed: 0.1
  limited_rot_speed: 0.4
  limited_distance: 0.3

