#!/bin/bash
xhost +
CMD="/bin/bash -i -c /root/albert_ws/start_albert.sh"
#CMD="/bin/bash -i -c /root/albert_ws/start_yahboom.sh"
#CMD="/bin/bash"

docker run -it \
--gpus all \
--runtime=nvidia \
--net=host \
--env="DISPLAY" \
--env="QT_X11_NO_MITSHM=1" \
--env="NO_AT_BRIDGE=1" \
--env="BASH_ENV=/root/.bashrc" \
-v /tmp/.X11-unix:/tmp/.X11-unix \
-v /home/jetson/temp:/root/temp \
-v /home/jetson/albert_ws:/root/albert_ws \
-v /dev/bus/usb/001/022:/dev/bus/usb/001/022 \
-v /dev/bus/usb/001/023:/dev/bus/usb/001/023 \
--device=/dev/myserial \
--device=/dev/ydlidar \
--device=/dev/astro_pro_plus \
--device=/dev/astro_pro_plus_rgb \
--device=/dev/input \
--device=/dev/video0 \
--device=/dev/video1 \
--device=/dev/video2 \
--device=/dev/camera_usb \
--device=/dev/camera_depth \
-p 9090:9090 \
-p 8888:8888 \
albert_image $CMD
