#!/bin/bash
xhost +
CMD="/bin/bash -i -c /root/albert_ws/start_albert.sh"
#CMD="/bin/bash -i -c /root/albert_ws/start_yahboom.sh"
#CMD="/bin/bash"

docker run -it \
--gpus all \
--runtime=nvidia \
--net=host \
--env="DISPLAY" \
--env="QT_X11_NO_MITSHM=1" \
--env="NO_AT_BRIDGE=1" \
--env="BASH_ENV=/root/.bashrc" \
-v /tmp/.X11-unix:/tmp/.X11-unix \
-v /home/jetson/temp:/root/temp \
-v /home/jetson/albert_ws:/root/albert_ws \
